import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import UserProvider from "@/contexts/UserContext";
import AlertProvider from "@/contexts/AlertContext";
import GlobalAlert from "@/components/GlobalAlert";

const inter = Inter({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-gray-50`}
      >
        <AlertProvider>
          <UserProvider>
            <Header />
            <main>
              <GlobalAlert />
              {children}
            </main>
          </UserProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
